name: Build and Lint

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --builtins="_"
          # Exit if any flake8 issue is found (errors or warnings)
          flake8 . --count --max-complexity=10 --max-line-length=88 --statistics

  flatpak:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: "libresudoku-devel.flatpak"
          manifest-path: "io.github.sepehr_rs.LibreSudoku.Devel.json"
          run-tests: "true"
          cache-key: flatpak-builder-${{ github.sha }}
